name: master-deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    if: github.repository == 'CreatiCoding/CreatiCoding'
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-master-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-master-build-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Update Version
        run: |
          echo "{ \"version\": \"$(git rev-parse HEAD)\" }" > web-version.json

      - name: Make Tree
        run: |
          tree -J > tree.json

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          rm -rf .git
          aws s3 sync . s3://data.creco.today/CreatiCoding --acl public-read
          aws cloudfront create-invalidation --distribution-id E1UA77V5KRISB --paths "/CreatiCoding/*"

      - name: alert to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
