name: main-deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    if: github.repository == 'CreatiCoding/CreatiCoding'
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-main-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-main-build-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Update Version
        run: |
          echo "{ \"version\": \"$(git rev-parse HEAD)\" }" > web-version.json

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          aws s3 sync . s3://data.creco.today/CreatiCoding --acl public-read
